config/routes.rb
Rails.application.routes.draw do
  root :to => 'categories#index'

  resources :categories do
    resources :meats
  end

  resources :meats do
    resources :reviews
  end

  resources :search, only: [:index]
  resources :admin, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :meats

  validates :name, :presence => true
end

app/models/meat.rb
class Meat < ActiveRecord::Base
  belongs_to :category
  has_many :reviews
  include PgSearch
  pg_search_scope :search, against: [:name, :description]

  def average_rating
    self.reviews.sum(:rating) / self.reviews.length
  end

  validates :name, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :meat

  validates :rating, :comment, :presence => true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :categories
  private
  def categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    randomIndex = rand(Meat.all.length)
    @featuredMeat = Meat.find(randomIndex + 1)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/meats_controller.rb
class MeatsController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @meat = @category.meats.new
  end

  def create
    @category = Category.find(params[:category_id])
    @meat = @category.meats.new(meat_params)
    if @meat.save
      redirect_to category_path(@meat.category)
    else
      render :new
    end
  end

  def show
    # @category = Category.find(params[:category_id])
    @meat = Meat.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @meat = Meat.find(params[:id])
  end

  def update
    @meat = Meat.find(params[:id])
    if @meat.update(meat_params)
      redirect_to category_path(@meat.category)
    else
      render :edit
    end
  end

  private
  def meat_params
    params.require(:meat).permit(:name, :description, :image, :weight, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @meat = Meat.find(params[:meat_id])
    @review = @meat.reviews.new
  end

  def create
    @meat = Meat.find(params[:meat_id])
    @review = @meat.reviews.new(review_params)
    if @review.save
      redirect_to category_meat_path(@meat.category, @meat)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].present?
      @search_results = Meat.search(params[:query])
    else
      @meats = Meat.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<%= link_to "Add a category", new_category_path %>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to "delete", category_path(category), :data => {:method => :delete} %>
    </li>
  <% end %>
</ul>

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h3>Today's featured Meat:</h3>

<h5><%=link_to @featuredMeat.name, category_meat_path(@featuredMeat.category, @featuredMeat)%></h5>
<%= image_tag(@featuredMeat.image) %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.name %>:</h1>


<ol>
  <% @category.meats.each do |meat| %>
    <%= link_to meat.name, category_meat_path(meat) %>
    <%= image_tag(meat.image, width: '200') %>
  <% end %>
</ol>

<%= link_to "Add a meat to " + @category.name, new_category_meat_path(@category, @meat) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand navbar-right" href="/">Meats</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <footer>
    <hr>
    <%= link_to "search", search_index_path %>
  </footer>
</html>

app/views/meats/ _form.html.erb
<%= render "layouts/errors", :object => @meat %>

app/views/meats/edit.html.erb
<%= render "layouts/errors", :object => @meat %>

  <%= form_for [@category, @meat] do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.text_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :weight %>
      <%= f.text_field :weight, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/meats/new.html.erb
<%= render "layouts/errors", :object => @meat %>

  <%= form_for [@category, @meat] do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.text_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :weight %>
      <%= f.text_field :weight, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/meats/show.html.erb
<h1><%= @meat.name %></h1>

<img src="<%= @meat.image %>" />

<h4> <%= @meat.description %>

<h5>$<%= @meat.price %></h5>

<h5>Weight: <%= @meat.weight %> lbs </h5>
<p><%= link_to "edit", edit_category_meat_path(@meat) %></p>

<hr>


<h3>Reviews:</h3>

<h4>Average rating: <%= @meat.average_rating %></h4>


<% @meat.reviews.each do |review| %>
<div class="well">
  <h5><%= review.rating %> stars</h5>
  <h6><%= review.comment %> </h6>
</div>
<% end %>

<%= link_to "add review", new_meat_review_path(@meat) %>

<hr>

<%= link_to "back", category_path(@meat.category) %>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@meat, @review] do |f| %>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_field :comment, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h3>Tell us how you feel about <%= @meat.name %></h3>

<%= render "form" %>

<hr>

<%= link_to "Back", category_meat_path(@meat.category, @meat) %>

app/views/search/index.html.erb
<h1>Search</h1>

<form action="/search" method="get">
  <label for="query">Term:</label>
  <input id="query" name="query" type="text">
  <button type="submit">Search</button>
</form>

<% if @search_results && @search_results != [] %>
  <% @search_results.each do |meat| %>
    <h6><%= link_to meat.name, category_meat_path(meat.category, meat) %></h6>
  <% end %>
<% elsif @search_results %>
  <h6>No results were found </h6>
<% end %>